# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/igorchem/LQQCMMtools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/igorchem/LQQCMMtools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/igorchem/LQQCMMtools/CMakeFiles /home/igorchem/LQQCMMtools/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/igorchem/LQQCMMtools/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lqqcmmtools

# Build rule for target.
lqqcmmtools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lqqcmmtools
.PHONY : lqqcmmtools

# fast build rule for target.
lqqcmmtools/fast:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/build
.PHONY : lqqcmmtools/fast

src/Line.o: src/Line.cpp.o

.PHONY : src/Line.o

# target to build an object file
src/Line.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/Line.cpp.o
.PHONY : src/Line.cpp.o

src/Line.i: src/Line.cpp.i

.PHONY : src/Line.i

# target to preprocess a source file
src/Line.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/Line.cpp.i
.PHONY : src/Line.cpp.i

src/Line.s: src/Line.cpp.s

.PHONY : src/Line.s

# target to generate assembly for a file
src/Line.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/Line.cpp.s
.PHONY : src/Line.cpp.s

src/MDprep.o: src/MDprep.cpp.o

.PHONY : src/MDprep.o

# target to build an object file
src/MDprep.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/MDprep.cpp.o
.PHONY : src/MDprep.cpp.o

src/MDprep.i: src/MDprep.cpp.i

.PHONY : src/MDprep.i

# target to preprocess a source file
src/MDprep.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/MDprep.cpp.i
.PHONY : src/MDprep.cpp.i

src/MDprep.s: src/MDprep.cpp.s

.PHONY : src/MDprep.s

# target to generate assembly for a file
src/MDprep.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/MDprep.cpp.s
.PHONY : src/MDprep.cpp.s

src/PDB.o: src/PDB.cpp.o

.PHONY : src/PDB.o

# target to build an object file
src/PDB.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/PDB.cpp.o
.PHONY : src/PDB.cpp.o

src/PDB.i: src/PDB.cpp.i

.PHONY : src/PDB.i

# target to preprocess a source file
src/PDB.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/PDB.cpp.i
.PHONY : src/PDB.cpp.i

src/PDB.s: src/PDB.cpp.s

.PHONY : src/PDB.s

# target to generate assembly for a file
src/PDB.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/PDB.cpp.s
.PHONY : src/PDB.cpp.s

src/QCinput.o: src/QCinput.cpp.o

.PHONY : src/QCinput.o

# target to build an object file
src/QCinput.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/QCinput.cpp.o
.PHONY : src/QCinput.cpp.o

src/QCinput.i: src/QCinput.cpp.i

.PHONY : src/QCinput.i

# target to preprocess a source file
src/QCinput.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/QCinput.cpp.i
.PHONY : src/QCinput.cpp.i

src/QCinput.s: src/QCinput.cpp.s

.PHONY : src/QCinput.s

# target to generate assembly for a file
src/QCinput.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/QCinput.cpp.s
.PHONY : src/QCinput.cpp.s

src/XYZ.o: src/XYZ.cpp.o

.PHONY : src/XYZ.o

# target to build an object file
src/XYZ.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/XYZ.cpp.o
.PHONY : src/XYZ.cpp.o

src/XYZ.i: src/XYZ.cpp.i

.PHONY : src/XYZ.i

# target to preprocess a source file
src/XYZ.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/XYZ.cpp.i
.PHONY : src/XYZ.cpp.i

src/XYZ.s: src/XYZ.cpp.s

.PHONY : src/XYZ.s

# target to generate assembly for a file
src/XYZ.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/XYZ.cpp.s
.PHONY : src/XYZ.cpp.s

src/atom.o: src/atom.cpp.o

.PHONY : src/atom.o

# target to build an object file
src/atom.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/atom.cpp.o
.PHONY : src/atom.cpp.o

src/atom.i: src/atom.cpp.i

.PHONY : src/atom.i

# target to preprocess a source file
src/atom.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/atom.cpp.i
.PHONY : src/atom.cpp.i

src/atom.s: src/atom.cpp.s

.PHONY : src/atom.s

# target to generate assembly for a file
src/atom.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/atom.cpp.s
.PHONY : src/atom.cpp.s

src/gamessInput.o: src/gamessInput.cpp.o

.PHONY : src/gamessInput.o

# target to build an object file
src/gamessInput.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/gamessInput.cpp.o
.PHONY : src/gamessInput.cpp.o

src/gamessInput.i: src/gamessInput.cpp.i

.PHONY : src/gamessInput.i

# target to preprocess a source file
src/gamessInput.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/gamessInput.cpp.i
.PHONY : src/gamessInput.cpp.i

src/gamessInput.s: src/gamessInput.cpp.s

.PHONY : src/gamessInput.s

# target to generate assembly for a file
src/gamessInput.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/gamessInput.cpp.s
.PHONY : src/gamessInput.cpp.s

src/geometry.o: src/geometry.cpp.o

.PHONY : src/geometry.o

# target to build an object file
src/geometry.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/geometry.cpp.o
.PHONY : src/geometry.cpp.o

src/geometry.i: src/geometry.cpp.i

.PHONY : src/geometry.i

# target to preprocess a source file
src/geometry.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/geometry.cpp.i
.PHONY : src/geometry.cpp.i

src/geometry.s: src/geometry.cpp.s

.PHONY : src/geometry.s

# target to generate assembly for a file
src/geometry.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/geometry.cpp.s
.PHONY : src/geometry.cpp.s

src/global.o: src/global.cpp.o

.PHONY : src/global.o

# target to build an object file
src/global.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/global.cpp.o
.PHONY : src/global.cpp.o

src/global.i: src/global.cpp.i

.PHONY : src/global.i

# target to preprocess a source file
src/global.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/global.cpp.i
.PHONY : src/global.cpp.i

src/global.s: src/global.cpp.s

.PHONY : src/global.s

# target to generate assembly for a file
src/global.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/global.cpp.s
.PHONY : src/global.cpp.s

src/interface.o: src/interface.cpp.o

.PHONY : src/interface.o

# target to build an object file
src/interface.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/interface.cpp.o
.PHONY : src/interface.cpp.o

src/interface.i: src/interface.cpp.i

.PHONY : src/interface.i

# target to preprocess a source file
src/interface.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/interface.cpp.i
.PHONY : src/interface.cpp.i

src/interface.s: src/interface.cpp.s

.PHONY : src/interface.s

# target to generate assembly for a file
src/interface.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/interface.cpp.s
.PHONY : src/interface.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/molecule.o: src/molecule.cpp.o

.PHONY : src/molecule.o

# target to build an object file
src/molecule.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/molecule.cpp.o
.PHONY : src/molecule.cpp.o

src/molecule.i: src/molecule.cpp.i

.PHONY : src/molecule.i

# target to preprocess a source file
src/molecule.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/molecule.cpp.i
.PHONY : src/molecule.cpp.i

src/molecule.s: src/molecule.cpp.s

.PHONY : src/molecule.s

# target to generate assembly for a file
src/molecule.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/molecule.cpp.s
.PHONY : src/molecule.cpp.s

src/mopacInput.o: src/mopacInput.cpp.o

.PHONY : src/mopacInput.o

# target to build an object file
src/mopacInput.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/mopacInput.cpp.o
.PHONY : src/mopacInput.cpp.o

src/mopacInput.i: src/mopacInput.cpp.i

.PHONY : src/mopacInput.i

# target to preprocess a source file
src/mopacInput.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/mopacInput.cpp.i
.PHONY : src/mopacInput.cpp.i

src/mopacInput.s: src/mopacInput.cpp.s

.PHONY : src/mopacInput.s

# target to generate assembly for a file
src/mopacInput.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/mopacInput.cpp.s
.PHONY : src/mopacInput.cpp.s

src/orcaInput.o: src/orcaInput.cpp.o

.PHONY : src/orcaInput.o

# target to build an object file
src/orcaInput.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/orcaInput.cpp.o
.PHONY : src/orcaInput.cpp.o

src/orcaInput.i: src/orcaInput.cpp.i

.PHONY : src/orcaInput.i

# target to preprocess a source file
src/orcaInput.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/orcaInput.cpp.i
.PHONY : src/orcaInput.cpp.i

src/orcaInput.s: src/orcaInput.cpp.s

.PHONY : src/orcaInput.s

# target to generate assembly for a file
src/orcaInput.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/orcaInput.cpp.s
.PHONY : src/orcaInput.cpp.s

src/pdbAtom.o: src/pdbAtom.cpp.o

.PHONY : src/pdbAtom.o

# target to build an object file
src/pdbAtom.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/pdbAtom.cpp.o
.PHONY : src/pdbAtom.cpp.o

src/pdbAtom.i: src/pdbAtom.cpp.i

.PHONY : src/pdbAtom.i

# target to preprocess a source file
src/pdbAtom.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/pdbAtom.cpp.i
.PHONY : src/pdbAtom.cpp.i

src/pdbAtom.s: src/pdbAtom.cpp.s

.PHONY : src/pdbAtom.s

# target to generate assembly for a file
src/pdbAtom.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/pdbAtom.cpp.s
.PHONY : src/pdbAtom.cpp.s

src/pdbModel.o: src/pdbModel.cpp.o

.PHONY : src/pdbModel.o

# target to build an object file
src/pdbModel.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/pdbModel.cpp.o
.PHONY : src/pdbModel.cpp.o

src/pdbModel.i: src/pdbModel.cpp.i

.PHONY : src/pdbModel.i

# target to preprocess a source file
src/pdbModel.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/pdbModel.cpp.i
.PHONY : src/pdbModel.cpp.i

src/pdbModel.s: src/pdbModel.cpp.s

.PHONY : src/pdbModel.s

# target to generate assembly for a file
src/pdbModel.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/pdbModel.cpp.s
.PHONY : src/pdbModel.cpp.s

src/residue.o: src/residue.cpp.o

.PHONY : src/residue.o

# target to build an object file
src/residue.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/residue.cpp.o
.PHONY : src/residue.cpp.o

src/residue.i: src/residue.cpp.i

.PHONY : src/residue.i

# target to preprocess a source file
src/residue.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/residue.cpp.i
.PHONY : src/residue.cpp.i

src/residue.s: src/residue.cpp.s

.PHONY : src/residue.s

# target to generate assembly for a file
src/residue.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/residue.cpp.s
.PHONY : src/residue.cpp.s

src/traj_analysis.o: src/traj_analysis.cpp.o

.PHONY : src/traj_analysis.o

# target to build an object file
src/traj_analysis.cpp.o:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/traj_analysis.cpp.o
.PHONY : src/traj_analysis.cpp.o

src/traj_analysis.i: src/traj_analysis.cpp.i

.PHONY : src/traj_analysis.i

# target to preprocess a source file
src/traj_analysis.cpp.i:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/traj_analysis.cpp.i
.PHONY : src/traj_analysis.cpp.i

src/traj_analysis.s: src/traj_analysis.cpp.s

.PHONY : src/traj_analysis.s

# target to generate assembly for a file
src/traj_analysis.cpp.s:
	$(MAKE) -f CMakeFiles/lqqcmmtools.dir/build.make CMakeFiles/lqqcmmtools.dir/src/traj_analysis.cpp.s
.PHONY : src/traj_analysis.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... lqqcmmtools"
	@echo "... edit_cache"
	@echo "... src/Line.o"
	@echo "... src/Line.i"
	@echo "... src/Line.s"
	@echo "... src/MDprep.o"
	@echo "... src/MDprep.i"
	@echo "... src/MDprep.s"
	@echo "... src/PDB.o"
	@echo "... src/PDB.i"
	@echo "... src/PDB.s"
	@echo "... src/QCinput.o"
	@echo "... src/QCinput.i"
	@echo "... src/QCinput.s"
	@echo "... src/XYZ.o"
	@echo "... src/XYZ.i"
	@echo "... src/XYZ.s"
	@echo "... src/atom.o"
	@echo "... src/atom.i"
	@echo "... src/atom.s"
	@echo "... src/gamessInput.o"
	@echo "... src/gamessInput.i"
	@echo "... src/gamessInput.s"
	@echo "... src/geometry.o"
	@echo "... src/geometry.i"
	@echo "... src/geometry.s"
	@echo "... src/global.o"
	@echo "... src/global.i"
	@echo "... src/global.s"
	@echo "... src/interface.o"
	@echo "... src/interface.i"
	@echo "... src/interface.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/molecule.o"
	@echo "... src/molecule.i"
	@echo "... src/molecule.s"
	@echo "... src/mopacInput.o"
	@echo "... src/mopacInput.i"
	@echo "... src/mopacInput.s"
	@echo "... src/orcaInput.o"
	@echo "... src/orcaInput.i"
	@echo "... src/orcaInput.s"
	@echo "... src/pdbAtom.o"
	@echo "... src/pdbAtom.i"
	@echo "... src/pdbAtom.s"
	@echo "... src/pdbModel.o"
	@echo "... src/pdbModel.i"
	@echo "... src/pdbModel.s"
	@echo "... src/residue.o"
	@echo "... src/residue.i"
	@echo "... src/residue.s"
	@echo "... src/traj_analysis.o"
	@echo "... src/traj_analysis.i"
	@echo "... src/traj_analysis.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

